'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
'
Namespace com.cdyne.ws
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="evSoap", [Namespace]:="http://ws.cdyne.com/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(System.Object()))>  _
    Public Class ev
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://ws.cdyne.com/emailverify/ev.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.cdyne.com/VerifyEmail", RequestNamespace:="http://ws.cdyne.com/", ResponseNamespace:="http://ws.cdyne.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function VerifyEmail(ByVal email As String) As ReturnIndicator
            Dim results() As Object = Me.Invoke("VerifyEmail", New Object() {email})
            Return CType(results(0),ReturnIndicator)
        End Function
        
        '<remarks/>
        Public Function BeginVerifyEmail(ByVal email As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("VerifyEmail", New Object() {email}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndVerifyEmail(ByVal asyncResult As System.IAsyncResult) As ReturnIndicator
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ReturnIndicator)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.cdyne.com/ReturnCodes", RequestNamespace:="http://ws.cdyne.com/", ResponseNamespace:="http://ws.cdyne.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReturnCodes() As Object()
            Dim results() As Object = Me.Invoke("ReturnCodes", New Object(-1) {})
            Return CType(results(0),Object())
        End Function
        
        '<remarks/>
        Public Function BeginReturnCodes(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ReturnCodes", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndReturnCodes(ByVal asyncResult As System.IAsyncResult) As Object()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Object())
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://ws.cdyne.com/")>  _
    Public Class ReturnIndicator
        
        '<remarks/>
        Public ResponseText As String
        
        '<remarks/>
        Public ResponseCode As Integer
        
        '<remarks/>
        Public LastMailServer As String
    End Class
End Namespace
